server:
  port: 8003
spring:
  application:
    name: candidate-ui
  freemarker:
    cache: false
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: 47.93.248.210
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka