server:
  port: 8003
spring:
  application:
    name: candidate-ui
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka